### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by RealIndica** [Geri-Borbas/.NET.Library.TuyaKit#3]
Hey I used this a while ago and I starting programming an application using this library, but it doesn't seem to work. 
Exception I get when running [devicename].Toggle() :

System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)

Any ideas?

edit:

Seems there is no support for 3.3 protocol. I'll see what I can do though.

**Comment by RealIndica** [comment]
7 hours later, still no luck whatsoever. I have messaged you on twitter for guidence.

Cheers

**Comment by Geri-Borbas** [comment]
Hey there, I'm no longer support this repository, as I'm working on the Swift port right now. Debugging Tuya devices can be challenging indeed. I used Wireshark to see/capture the raw packets, then you can create tests against it. This may work for you as well.  🤷‍♂️

**Comment by RealIndica** [comment]
Got it working and created a pull request :)
