### ISSUE TITLE
3.3 support

### ISSUE THREAD

**Issue by RealIndica** [Geri-Borbas/.NET.Library.TuyaKit#5]
Hi!

I added protocol 3.3 support and repetition of dropped requests to prevent exceptions.

Would you be able to add this?

If not, I would be willing to start a new project inspired by your code.

Thank you :)

**Comment by Geri-Borbas** [comment]
Thanks for the headsup, I have not much time to review the code, feel free to create a new project with this.
Regarding Tuya protocols we are all inspired by [TuyaAPI](https://github.com/codetheweb/tuyapi ) from [Max Isom](https://maxisom.me/) anyway. 😄

**Comment by RealIndica** [comment]
> Thanks for the headsup, I have not much time to review the code, feel free to create a new project with this.
> Regarding Tuya protocols we are all inspired by [TuyaAPI](https://github.com/codetheweb/tuyapi) from [Max Isom](https://maxisom.me/) anyway. 😄

Haha yes!

Thank you for the inspiration and I can't wait for your future releases :)
